apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  labels:
    volume: nginx-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nginx/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: nginx-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual 
