apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica1
  template:
    metadata:
      labels:
        app: replica1
    spec:
      containers:
      - name: container1
        image: wotkddl21/dockertest
        ports:
        - containerPort: 3000
