apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2
spec:
  selector:
    matchLabels:
      app: pod2
  template:
    metadata:
      labels:
        app: pod2
    spec:
      containers:
      - name: container2
        image: {dockerhub username}/dockertest2  # ex) sangsoodong/dockertest2 
        ports:
        - containerPort: 3000
